import Link from "next/link";

import styles from "../styles/page.module.css";
import TopicCard from "@/components/topicCard/TopicCard";
import Head from "next/head";
import { trpc } from "@/utils/trpc";
import { useSession } from "next-auth/react";

export default function Home() {
  const { data: sessionData } = useSession();

  const { data, status } = trpc.getTopics.useQuery(sessionData?.user.id);

  let voteMutation = trpc.voteForTopic.useMutation()

  return (
    <>
      <Head>
        <title>GFT Ballot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.votingarea}>
          <Link href={"/pitch"} className={styles.cta}>
            Pitch your own
          </Link>
          {status === "success" ? (
            data.map((topic) => {
              const hasUserVotedOn = topic.votedBy.some(
                (vote) => vote.id === sessionData?.user.id
              );
              let onClickHandler = voteMutation.mutate.bind(null, {tid: topic.id, uid: sessionData?.user.id});
              return (
                <TopicCard key={topic.id} topic={topic} hasVoted={hasUserVotedOn} onClick={onClickHandler} />
              );
            })
          ) : (
            <span>Please wait while loading data...</span>
          )}
        </section>
      </main>
    </>
  );
}
